'use strict';

import keyMirror from 'keymirror';

export default keyMirror({
	BROWSER_ACTION: null,
	SHOW_ONCOURSE_COMPONENT: null,
	HIDE_ONCOURSE_COMPONENT: null,
	APP_STORE_UPDATED: null,
	USER_INFORMATION_UPDATED: null,
	USER_STORE_UPDATED: null,
	REQUEST_USER_INFORMATION: null,
	START_AUTH_FLOW: null,
	ISSUES_STORE_UPDATED: null,
	REPOS_STORE_UPDATED: null,
	MILESTONES_STORE_UPDATED: null,
	OPEN_NEW_TAB: null,
	UPDATE_FILTER: null
});
